chg: lab2/answers/task1

diff --git a/lab2/answers/task1 b/lab2/answers/task1
--- a/lab2/answers/task1
+++ b/lab2/answers/task1
@@ -1,4 +1,32 @@
 #! /bin/bash
 
-cd /home/alexandr/GitRepos/os_lab_2019/lab2/src/swap
-gcc swap.c main.c -o Swap
+function smart_exit() {
+    if [[ $1 -ne 0 ]]; then
+    shift
+    echo $*
+    fi   
+}
+
+# exit when any command fails
+set -e
+# keep track of the last executed command
+trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
+# echo an error message before exiting
+# trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT
+trap 'smart_exit $? "\"${last_command}\" command filed with exit code $?."' EXIT
+# nice_echo include
+. /home/alexandr/Documents/scripts/nice_echo
+
+lm_echo "task1"
+
+LAB_PATH=/home/alexandr/GitRepos/os_lab_2019/lab2/src
+
+cd $LAB_PATH/swap
+lb_echo "---PWD: $(pwd)"
+
+lg_echo "---Compile swap"
+gcc swap.c main.c -o swap
+
+lb_echo "---Run swap"
+./swap
+
